### ISSUE TITLE
電腦輔助設計實習課程 Q and A

### ISSUE THREAD

**Issue by mdecourse** [mdecourse/cad2019#5]
與電腦輔助設計實習課程有關的問題, 請在此提出.

**Comment by s40623252** [comment]
40623252李展齊

**Comment by s40723103** [comment]
edit Y:\tmp\solvespace\extlib\angle\CMakeLists.txt comment out line 713 and 714

#list(APPEND ANGLE_DEFINITIONS
#"-DANGLE_PRELOADED_D3DCOMPILER_MODULE_NAMES={ \"d3dcompiler_47.dll\", \"d3dcompiler_46.dll\", \"d3dcompiler_43.dll\" }")
endif()
使用SciTe時，請問打開CMakeLists檔案為什麼要暫時註解指令?

**Comment by s40623252** [comment]
40623252李展齊 變為2a第5組

**Comment by s40523241** [comment]
為什麼cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release
mingw32-make無法執行

**Comment by s40723238** [comment]
我打ffmepg在命令字元上，它說'ffmpeg' 不是內部或外部命令、可執行的程式或批次檔。
請問這是甚麼問題?

**Comment by mdecourse** [comment]
Q:
我Y槽和隨身硬碟的shareX都有ffmpeg.exe的檔案，但是當我上好字幕，改好指令，打在命令字元的時候，它卻顯示'ffmpeg' 不是內部或外部命令、可執行的程式或批次檔。
請問老師我的命令字元要怎樣才能執行ffmpeg的指令?

A:
在命令列必須將 ffmpeg.exe 的路徑, 加入 Path 搜尋設定, 或者直接進入 ffmpeg.exe 所在目錄執行.

**Comment by s40723103** [comment]
Question:
1.請問倉儲改版上傳後但下一次準備進行改版卻無法執行指令動作。
例:git push 無法執行指令

2.有時要進入近端時無法連接，看了ipv伺服器網址也沒問題，也有嘗試註解掉網址看是否能連接成功，http放入SciTe裡去操作也可以進行動作，但無法在code裡執行。

**Comment by s40723150** [comment]
遠端的 github pages 坎入 STL 無法顯示模型，但近端的動態和靜態都可以正常顯示。

**Comment by s40723103** [comment]
Q老師不好意思我把時間聽成5.前繳交都可以，然而我在12.20分做好準備上傳發現已經關閉了，不知道能否在今天老師醒來前發這封信還來不來的及

以下是我的影片網址:
https://www.youtube.com/watch?v=KCq9y73_UIY&t=8s 

以及網頁網址:
https://s40723103.github.io/cad2019/blog/index.html

**Comment by s40723238** [comment]
我在學校弄好ssh之後回家想git push他卻顯示
FATAL ERROR: Network error: Network is unreachable
fatal: Could not read from remote repository.

Please make sure you have the correct access rights and the repository exists.
我試過關proxy或是關ipv 6但是都還是一樣，請問他說我沒有權限跟搜尋不到網路是怎麼回事?

**Comment by s40723238** [comment]
1.要怎麼檢視private key為putty讀取的格式，當初產生.ppk的private key不就是puttygen出來的嗎?
2.老師的每一步都有做了，權還是顯示
FATAL ERROR: Network error: Network is unreachable
fatal: Could not read from remote repository.

Please make sure you have the correct access rights and the repository exists.
之前使用普通的git push都沒有問題，請問用這ssh連線除了push的時候不用打帳號密碼還有其他功用嗎?

**Comment by s40723238** [comment]
我用putty.exe設定把proxy關掉，也有確實指向我的.PPK私人鑰，open的時候卻出現
no supported authentication methods available(sent:public key)
我push的時候它顯示everything is up to date無法對我的網站進行正確的更新，抱歉一直提出ssh的問題，但這問題已經對我的網站和生活產生影響了

**Comment by s40723212** [comment]
昨天提交問題已解決
一樣使用add,commit,push，在這過程中只要用到generate_pages就會像昨天一樣無法提交
這是成功pull的code
Microsoft Windows [Version 10.0.18362.535]
(c) 2019 Microsoft Corporation. All rights reserved.

Y:\>F:

F:\201906_fall>cd cad2019
The system cannot find the path specified.

F:\201906_fall>cd ..

F:\>cd cad2019bg1

F:\cad2019bg1>git pull
remote: Enumerating objects: 19, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 22 (delta 16), reused 18 (delta 16), pack-reused 3
Unpacking objects: 100% (22/22), done.
From https://github.com/s40723212/cad2019bg1
   b773e51..7d55fdf  master     -> origin/master
error: Your local changes to the following files would be overwritten by merge:
        content/week10-14.html
        content/week15-16.html
        content/week17-18.html
Please commit your changes or stash them before you merge.
error: The following untracked working tree files would be overwritten by merge:
        content/week17協同任務.html
        content/week18.html
        content/劉冠志.html
        content/曾信誠.html
        content/洪維辰.html
        content/高永霖&顏士勛.html
        images/modelTut15.jpg
        images/modelTut16.jpg
        images/modelTut17.jpg
        images/modelTut18.jpg
Please move or remove them before you merge.
Aborting

F:\cad2019bg1>git add .

F:\cad2019bg1>git commit -m "解決git pull 問題"
[master f323f5c] 解決git pull 問題
 14 files changed, 1268 insertions(+), 312 deletions(-)
 rewrite content/week10-14.html (69%)
 create mode 100644 "content/week17\345\215\224\345\220\214\344\273\273\345\213\231.html"
 create mode 100644 content/week18.html
 create mode 100644 "content/\345\212\211\345\206\240\345\277\227.html"
 copy content/week10-14.html => "content/\346\233\276\344\277\241\350\252\240.html" (66%)
 create mode 100644 "content/\346\264\252\347\266\255\350\276\260.html"
 create mode 100644 "content/\347\254\254\345\205\253\347\253\240"
 create mode 100644 "content/\351\253\230\346\260\270\351\234\226&\351\241\217\345\243\253\345\213\233.html"
 create mode 100644 images/modelTut15.jpg
 create mode 100644 images/modelTut16.jpg
 create mode 100644 images/modelTut17.jpg
 create mode 100644 images/modelTut18.jpg

F:\cad2019bg1>git push
Username for 'https://github.com': s40723212
Password for 'https://s40723212@github.com':
To https://github.com/s40723212/cad2019bg1
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/s40723212/cad2019bg1'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

F:\cad2019bg1>git pull
Auto-merging content/week17-18.html
CONFLICT (content): Merge conflict in content/week17-18.html
Auto-merging content/week15-16.html
CONFLICT (content): Merge conflict in content/week15-16.html
Automatic merge failed; fix conflicts and then commit the result.

F:\cad2019bg1>git add .

F:\cad2019bg1>git commit -m "解決git pull 問題"
[master 642dbee] 解決git pull 問題

F:\cad2019bg1>git push
Username for 'https://github.com': s40723212
Password for 'https://s40723212@github.com':
Enumerating objects: 19, done.
Counting objects: 100% (19/19), done.
Delta compression using up to 8 threads
Compressing objects: 100% (11/11), done.
Writing objects: 100% (11/11), 2.25 KiB | 2.25 MiB/s, done.
Total 11 (delta 8), reused 0 (delta 0)
remote: Resolving deltas: 100% (8/8), completed with 6 local objects.
To https://github.com/s40723212/cad2019bg1
   7d55fdf..642dbee  master -> master

F:\cad2019bg1>
